### ISSUE TITLE
Readme seems to end suddenly, doesn't mention anything other that Auth.

### ISSUE THREAD

**Issue by bruceburge** [microsoftgraph/console-calendar-sample#4]
There is a lab.md that seems to have more information, but its not referenced, and the code in the project differs from both.

Having a good clean, consistent, documented example would really be useful.

**Comment by jasonjoh** [comment]
We are archiving this sample and closing this issue. For a full .NET console app sample, please see https://github.com/microsoftgraph/msgraph-training-dotnet-core
